### ISSUE TITLE
Does it support Asynchronous I/O?

### ISSUE THREAD

**Issue by JoshYuJump** [jpsca/sqla-wrapper#41]
As we know it's base on SQLAlchemy 1.4 from 5.0.0, Asynchronous I/O is theoretically supported.

Would you provide some example using in `sqla-wrapper`?

**Comment by jpsca** [comment]
Sorry, it doesn't support asynchronous I/O yet. There are no plans to add the support either, but I would happily accept a pull request for that feature.
