### ISSUE TITLE
Incompatible with just-released SQLAlchemy 2.0

### ISSUE THREAD

**Issue by wonderbeyond** [jpsca/sqla-wrapper#42]
Partial of the traceback:

> ...
>     db = SQLAlchemy(
>          ^^^^^^^^^^^
>   File "/home/ubuntu/workspace/nb/.venv/lib/python3.11/site-packages/sqla_wrapper/sqlalchemy_wrapper.py", line 94, in __init__
>     self._include_sqlalchemy()
>   File "/home/ubuntu/workspace/nb/.venv/lib/python3.11/site-packages/sqla_wrapper/sqlalchemy_wrapper.py", line 126, in _include_sqlalchemy
>     for key in module.__all__:
>                ^^^^^^^^^^^^^^
> AttributeError: module 'sqlalchemy' has no attribute '__all__'. Did you mean: '__file__'?

**Comment by jpsca** [comment]
Fixed with last release

**Comment by wonderbeyond** [comment]
seems it was a hard work ❤️
